### ISSUE TITLE
CountryCode and Currency missing nil check

### ISSUE THREAD

**Issue by ehannes** [my-codeworks/fortnox-api#29]
When trying to find a `Customer`, I get this error:
```
  1) Fortnox::API::Customer#find returns 1 Customer
     Failure/Error: super country_code.upcase[0...2]
     
     NoMethodError:
       undefined method `upcase' for nil:NilClass
     # ./lib/fortnox/api/models/attributes/country_code.rb:12:in `country_code='
     # ./lib/fortnox/api/models/base.rb:29:in `initialize'
     # ./lib/fortnox/api/repositories/base.rb:27:in `new'
     # ./lib/fortnox/api/repositories/base.rb:27:in `instansiate'
     # ./lib/fortnox/api/repositories/base/json_convertion.rb:10:in `hash_to_entity'
     # ./lib/fortnox/api/repositories/base/loaders.rb:37:in `find_one_by'
     # ./lib/fortnox/api/repositories/base/loaders.rb:28:in `find'
     # ./lib/fortnox/api/customer.rb:26:in `find'
     # ./spec/fortnox/api/customer_spec.rb:42:in `block (4 levels) in <top (required)>'
     # ./spec/fortnox/api/customer_spec.rb:42:in `block (3 levels) in <top (required)>'
     # ./spec/fortnox/api/customer_spec.rb:46:in `block (3 levels) in <top (required)>'
```

If attribute `CountryCode` or `Currency` is nil, the following lines will raise `NoMethodError`:

`Currency`:
```
def currency=( currency )
  super currency.upcase[0...3]
end
```

`CountryCode`:
```
def country_code=( country_code )
  super country_code.upcase[0...2]
end
```

It would be great if this could be covered in attribute specs.

**Comment by ehannes** [comment]
Fix will be included in #23
